
GET http://127.0.0.1:8000/user/products/ HTTP/1.1

###

POST http://127.0.0.1:8000/user/products/ HTTP/1.1
Content-Type: application/json

{
      
            "name": "product1",
            "price": 100,
            "description": "description1",
            "stock": 10
}


###

POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin" 
}

###

POST http://127.0.0.1:8000/user/user/
Content-Type: application/json

{
    "username": "admin1",
    "password": "admin1"
}